# Generated by Django 4.0.6 on 2022-08-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='al_category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mb_category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AlCategory',
        ),
        migrations.DeleteModel(
            name='MbCategory',
        ),
    ]
