# Generated by Django 4.0.6 on 2022-08-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_al_category_alter_product_mb_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alchol_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, null=True),
        ),
    ]
