# Generated by Django 4.0.6 on 2022-08-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_project_productlike_product_and_more'),
        ('products', '0004_alter_product_alchol_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.review'),
        ),
    ]
