# Generated by Django 4.0.6 on 2022-08-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alchol_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True),
        ),
    ]
